[package]
name = "rust_axum_project"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
serde = "1.0.228"
serde_json = "1.0"
jsonwebtoken = { version = "10.1.0", features = ["aws_lc_rs"] }
chrono = "0.4.42"




